name: Justinbrackett
favicon: null
layout_spectrum: 0.8892948965076357
typography_spectrum: 0.06410406366921961
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5869681113399565
  lightness: 0.5350131241139024
  saturation: 0.28558126860298216
  rhythmicContrast: 0.33757910621352494
purpose: []
